[workspace]
members = [
  'node',
  'utils/ethereum',
  'utils/convertor',
  'utils/currency',
  'utils/dummy',
  'runtime/devnet',
  'runtime/gaki-testnet',
  'runtime/template',
  'pallets/player',
  'pallets/upfront-pool',
  'pallets/pool',
  'pallets/staking-pool',
  'pallets/gafi-tx',
  'pallets/address-mapping',
  'pallets/pallet-faucet',
  'pallets/sponsored-pool',
  'pallets/pallet-cache',
  'pallets/game-creator',
  'tests',
  'primitives',
]
[profile.release]
panic = 'unwind'

[patch.crates-io]

evm-core = {git = "https://github.com/cryptoviet/evm", branch = "master"}

ethereum = {git = "https://github.com/cryptoviet/ethereum", branch = "master"}
